tls:
  options:
    default:
      minVersion: VersionTLS11
    secure:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
http:
  middlewares:
    permissions-policy:
      headers:
        customResponseHeaders:
          Permissions Policy: ""accelerometer=(); ambient-light-sensor=(); autoplay=(self); camera=(); encrypted-media=(); fullscreen=(self); geolocation=(*); gyroscope=(); magnetometer=(); microphone=(); midi=(); payment=(); picture-in-picture=(*); speaker=(); sync-xhr=(); usb=(); vr=()interest-cohort=(); ""
          X-Xss-Protection: ""1; mode=block""
          Strict-Transport-Security: ""max-age=31536000; includeSubDomain""
          Content-Security-Policy: ""upgrade-insecure-requests""
          X-Frame-Options: ""SAMEORIGIN""
          Referrer-Policy: ""strict-origin-when-cross-origin""
          Cache-Control: ""public, max-age=15, must-revalidate""
